test_IsoOrderedGenerator:
	clang -L . -l IsoSpec++ test_IsoOrderedGenerator.c -lpthread -o IsoOrderedGenerator

test_IsoLayeredGenerator:
	clang -L . -l IsoSpec++ test_IsoLayeredGenerator.c -lpthread -o IsoLayeredGenerator
