title: Isospec
description: Hyperfast Isotopic Structure Calculator.
google_analytics: 
show_downloads: true
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions

width: large
orientation: landscape
