# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rinterface <- function(isotopeNumbers, atomCounts, isotopeMasses, isotopeProbabilities, stopCondition, algo = 0L, tabSize = 1000L, hashSize = 1000L, step = .25) {
    .Call('IsoSpecR_Rinterface', PACKAGE = 'IsoSpecR', isotopeNumbers, atomCounts, isotopeMasses, isotopeProbabilities, stopCondition, algo, tabSize, hashSize, step)
}

