# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get the bloody solution.
#' 
#' @param isotopeNumbers bla
#' @param atomCounts bli
#' @param isotopeMasses dupa
#' @param isotopeProbabilities gowno
#' @param cutOff
#' @param tabSize
#' @param hashSize
#' @param step
#' @export
stupidRinterface <- function(isotopeNumbers, atomCounts, isotopeMasses, isotopeProbabilities, cutOff, tabSize = 1000L, hashSize = 1000L, step = .25) {
    .Call('IsoSpecR_stupidRinterface', PACKAGE = 'IsoSpecR', isotopeNumbers, atomCounts, isotopeMasses, isotopeProbabilities, cutOff, tabSize, hashSize, step)
}

