test_IsoThresholdGenerator:
	clang++ -std=c++11 -x c++ test_IsoThresholdGenerator.c -o isoThreshold

test_IsoOrderedGenerator:
	clang++ -std=c++11 -x c++ test_IsoOrderedGenerator.c -o isoOrdered

test_IsoOrderedArray:
	clang++ -std=c++11 -x c++ test_arrays.c -o isoOrderedArray
