// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// stupidRinterface
List stupidRinterface(IntegerVector isotopeNumbers, IntegerVector atomCounts, NumericVector isotopeMasses, NumericVector isotopeProbabilities, double cutOff, int tabSize, int hashSize, double step);
RcppExport SEXP IsoSpecR_stupidRinterface(SEXP isotopeNumbersSEXP, SEXP atomCountsSEXP, SEXP isotopeMassesSEXP, SEXP isotopeProbabilitiesSEXP, SEXP cutOffSEXP, SEXP tabSizeSEXP, SEXP hashSizeSEXP, SEXP stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type isotopeNumbers(isotopeNumbersSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type atomCounts(atomCountsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type isotopeMasses(isotopeMassesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type isotopeProbabilities(isotopeProbabilitiesSEXP);
    Rcpp::traits::input_parameter< double >::type cutOff(cutOffSEXP);
    Rcpp::traits::input_parameter< int >::type tabSize(tabSizeSEXP);
    Rcpp::traits::input_parameter< int >::type hashSize(hashSizeSEXP);
    Rcpp::traits::input_parameter< double >::type step(stepSEXP);
    __result = Rcpp::wrap(stupidRinterface(isotopeNumbers, atomCounts, isotopeMasses, isotopeProbabilities, cutOff, tabSize, hashSize, step));
    return __result;
END_RCPP
}
