# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rinterface <- function(molecule, isotopes, stopCondition, algo = 0L, tabSize = 1000L, hashSize = 1000L, step = .3, showCounts = FALSE, trim = TRUE, charge = 1.0) {
    .Call('_IsoSpecR_Rinterface', PACKAGE = 'IsoSpecR', molecule, isotopes, stopCondition, algo, tabSize, hashSize, step, showCounts, trim, charge)
}

RParsePeptideSequence <- function(sequence, unimod_db_path = "") {
    .Call('_IsoSpecR_RParsePeptideSequence', PACKAGE = 'IsoSpecR', sequence, unimod_db_path)
}

RIsotopicTable <- function() {
    .Call('_IsoSpecR_RIsotopicTable', PACKAGE = 'IsoSpecR')
}

