name: Build

on:
  push:
    branches:
#      - version_2_2
      - ci_wheels
    tags:
      - v*

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-20.04, windows-2019, macos-10.15]
        os: [windows-latest, macos-14]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        env:
          GITHUB_BUILDING_WHEELS: 1

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
