.TH "IsoSpec::OrderMarginalsBySizeDecresing" 3 "Tue Oct 30 2018" "Version 1.95" "IsoSpec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsoSpec::OrderMarginalsBySizeDecresing
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOrderMarginalsBySizeDecresing\fP (\fBPrecalculatedMarginal\fP const *const *_T)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (int m1, int m2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 128 of file operators\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IsoSpec from the source code\&.
