.TH "IsoSpec::IsoOrderedGenerator" 3 "Tue Oct 30 2018" "Version 1.95" "IsoSpec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsoSpec::IsoOrderedGenerator \- The generator of isotopologues sorted by their probability of occurrence\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <isoSpec++\&.h>\fP
.PP
Inherits \fBIsoSpec::IsoGenerator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBadvanceToNextConfiguration\fP () override final"
.br
.RI "Advance to the next, not yet visited, most probable isotopologue\&. "
.ti -1c
.RI "void \fBget_conf_signature\fP (int *space) const override final"
.br
.RI "Save the counts of isotopes in the space\&. "
.ti -1c
.RI "\fBIsoOrderedGenerator\fP (\fBIso\fP &&iso, int _tabSize=1000, int _hashSize=1000)"
.br
.RI "The move-contstructor\&. "
.ti -1c
.RI "virtual \fB~IsoOrderedGenerator\fP ()"
.br
.RI "Destructor\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The generator of isotopologues sorted by their probability of occurrence\&. 

The subsequent isotopologues are generated with diminishing probability, starting from the mode\&. This algorithm take O(N*log(N)) to compute the N isotopologues because of using the Priority Queue data structure\&. Obtaining the N isotopologues can be achieved in O(N) if they are not required to be spit out in the descending order\&. 
.PP
Definition at line 179 of file isoSpec++\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool IsoSpec::IsoOrderedGenerator::advanceToNextConfiguration ()\fC [final]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Advance to the next, not yet visited, most probable isotopologue\&. 
.PP
\fBReturns:\fP
.RS 4
Return false if it is not possible to advance\&. 
.RE
.PP

.PP
Implements \fBIsoSpec::IsoGenerator\fP\&.
.PP
Definition at line 461 of file isoSpec++\&.cpp\&.
.SS "void IsoSpec::IsoOrderedGenerator::get_conf_signature (int * space) const\fC [inline]\fP, \fC [final]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Save the counts of isotopes in the space\&. 
.PP
\fBParameters:\fP
.RS 4
\fIspace\fP An array where counts of isotopes shall be written\&. Must be as big as the overall number of isotopes\&. 
.RE
.PP

.PP
Implements \fBIsoSpec::IsoGenerator\fP\&.
.PP
Definition at line 202 of file isoSpec++\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IsoSpec from the source code\&.
