.TH "IsoSpec::MarginalTrek" 3 "Tue Oct 30 2018" "Version 1.95" "IsoSpec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsoSpec::MarginalTrek \- The marginal distribution class (a subisotopologue)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <marginalTrek++\&.h>\fP
.PP
Inherits \fBIsoSpec::Marginal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMarginalTrek\fP (\fBMarginal\fP &&m, int tabSize=1000, int hashSize=1000)"
.br
.RI "Move constructor: specializes the \fBMarginal\fP class\&. "
.ti -1c
.RI "bool \fBprobeConfigurationIdx\fP (int idx)"
.br
.RI "Check if the table of computed subisotopologues does not have to be extended\&. "
.ti -1c
.RI "int \fBprocessUntilCutoff\fP (double cutoff)"
.br
.RI "Calculate subisotopologues with probability above or equal to the cut-off\&. "
.ti -1c
.RI "const std::vector< double > & \fBconf_lprobs\fP () const"
.br
.ti -1c
.RI "const std::vector< double > & \fBconf_masses\fP () const"
.br
.ti -1c
.RI "const std::vector< int * > & \fBconfs\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The marginal distribution class (a subisotopologue)\&. 
.PP
Definition at line 141 of file marginalTrek++\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IsoSpec::MarginalTrek::MarginalTrek (\fBMarginal\fP && m, int tabSize = \fC1000\fP, int hashSize = \fC1000\fP)"

.PP
Move constructor: specializes the \fBMarginal\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fItabSize\fP The size of the table used to store configurations in the allocator\&. 
.br
\fIhashSize\fP The size of the hash table used to store visited subisotopologues\&. 
.RE
.PP

.PP
Definition at line 256 of file marginalTrek++\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool IsoSpec::MarginalTrek::probeConfigurationIdx (int idx)\fC [inline]\fP"

.PP
Check if the table of computed subisotopologues does not have to be extended\&. This function checks if the idx-th most probable subisotopologue was memoized and if not, computes it and memoizes it\&.
.PP
\fBParameters:\fP
.RS 4
\fIidx\fP The number of the idx-th most probable subisotopologue\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Returns false if it the provided idx exceeds the total number of subisotopologues\&. 
.RE
.PP

.PP
Definition at line 179 of file marginalTrek++\&.h\&.
.SS "int IsoSpec::MarginalTrek::processUntilCutoff (double cutoff)"

.PP
Calculate subisotopologues with probability above or equal to the cut-off\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcutoff\fP The probability cut-off 
.RE
.PP
\fBReturns:\fP
.RS 4
The number of the last subisotopologue above the cut-off\&. 
.RE
.PP

.PP
Definition at line 333 of file marginalTrek++\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IsoSpec from the source code\&.
