.TH "IsoSpec::LayeredMarginal" 3 "Thu Oct 11 2018" "Version 1.95" "IsoSpec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsoSpec::LayeredMarginal \- \fBLayeredMarginal\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <marginalTrek++\&.h>\fP
.PP
Inherits \fBIsoSpec::Marginal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLayeredMarginal\fP (\fBMarginal\fP &&m, int tabSize=1000, int hashSize=1000)"
.br
.RI "Move constructor: specializes the \fBMarginal\fP class\&. "
.ti -1c
.RI "bool \fBextend\fP (double new_threshold)"
.br
.RI "Extend the set of computed subisotopologues to those above the new threshold\&. "
.ti -1c
.RI "double \fBget_lProb\fP (int idx) const"
.br
.RI "get the log-probability of the idx-th subisotopologue, see details in \fBPrecalculatedMarginal::get_lProb\fP\&. "
.ti -1c
.RI "double \fBget_eProb\fP (int idx) const"
.br
.RI "get the probability of the idx-th subisotopologue, see details in \fBPrecalculatedMarginal::get_eProb\fP\&. "
.ti -1c
.RI "double \fBget_mass\fP (int idx) const"
.br
.RI "get the mass of the idx-th subisotopologue, see details in \fBPrecalculatedMarginal::get_mass\fP\&. "
.ti -1c
.RI "const Conf & \fBget_conf\fP (int idx) const"
.br
.RI "get the counts of isotopes that define the subisotopologue, see details in \fBPrecalculatedMarginal::get_conf\fP\&. "
.ti -1c
.RI "unsigned int \fBget_no_confs\fP () const"
.br
.RI "Get the number of precomputed subisotopologues, see details in \fBPrecalculatedMarginal::get_no_confs\fP\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBLayeredMarginal\fP class\&. 

An extendable version of the \fBPrecalculatedMarginal\fP, where you can extend the threshold at will\&. 
.PP
Definition at line 337 of file marginalTrek++\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IsoSpec::LayeredMarginal::LayeredMarginal (\fBMarginal\fP && m, int tabSize = \fC1000\fP, int hashSize = \fC1000\fP)"

.PP
Move constructor: specializes the \fBMarginal\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fItabSize\fP The size of the table used to store configurations in the allocator\&. 
.br
\fIhashSize\fP The size of the hash table used to store visited subisotopologues\&. 
.RE
.PP

.PP
Definition at line 445 of file marginalTrek++\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool IsoSpec::LayeredMarginal::extend (double new_threshold)"

.PP
Extend the set of computed subisotopologues to those above the new threshold\&. 
.PP
\fBParameters:\fP
.RS 4
\fInew_threshold\fP The new log-probability limiting the subisotopologues from below\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Returns false, if there are no fringe-subisotopologues (subisotopologues that were neighbours of the previously calculated subisotopologues, with log-probability below the previous threshold)\&. 
.RE
.PP

.PP
Definition at line 455 of file marginalTrek++\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IsoSpec from the source code\&.
