.TH "IsoSpec::Tabulator< T >" 3 "Tue Oct 30 2018" "Version 1.95" "IsoSpec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsoSpec::Tabulator< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTabulator\fP (T *generator, bool get_masses, bool get_probs, bool get_lprobs, bool get_confs)"
.br
.ti -1c
.RI "double * \fBmasses\fP ()"
.br
.ti -1c
.RI "double * \fBlprobs\fP ()"
.br
.ti -1c
.RI "double * \fBprobs\fP ()"
.br
.ti -1c
.RI "int * \fBconfs\fP ()"
.br
.ti -1c
.RI "size_t \fBconfs_no\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class IsoSpec::Tabulator< T >"

.PP
Definition at line 12 of file tabulator\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IsoSpec from the source code\&.
