.TH "IsoSpec::DirtyAllocator" 3 "Tue Oct 30 2018" "Version 1.95" "IsoSpec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsoSpec::DirtyAllocator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDirtyAllocator\fP (const int dim, const int tabSize=10000)"
.br
.ti -1c
.RI "void \fBshiftTables\fP ()"
.br
.ti -1c
.RI "void * \fBnewConf\fP ()"
.br
.ti -1c
.RI "void * \fBmakeCopy\fP (const void *conf)"
.br
.ti -1c
.RI "void * \fBmakeExternalCopy\fP (const void *conf)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file dirtyAllocator\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IsoSpec from the source code\&.
