.TH "IsoSpec::IsoSpec::TableOrder< T >" 3 "Thu Oct 11 2018" "Version 1.95" "IsoSpec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsoSpec::IsoSpec::TableOrder< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTableOrder\fP (const T *_tbl)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (unsigned int i, unsigned int j)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class IsoSpec::IsoSpec::TableOrder< T >"

.PP
Definition at line 174 of file operators\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IsoSpec from the source code\&.
