.TH "IsoSpec::Allocator< T >" 3 "Tue Oct 30 2018" "Version 1.95" "IsoSpec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsoSpec::Allocator< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAllocator\fP (const int dim, const int tabSize=10000)"
.br
.ti -1c
.RI "void \fBshiftTables\fP ()"
.br
.ti -1c
.RI "T * \fBnewConf\fP ()"
.br
.ti -1c
.RI "T * \fBmakeCopy\fP (const T *conf)"
.br
.ti -1c
.RI "T * \fBmakeExternalCopy\fP (const T *conf)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class IsoSpec::Allocator< T >"

.PP
Definition at line 34 of file allocator\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IsoSpec from the source code\&.
