.TH "IsoSpec::PrecalculatedMarginal" 3 "Tue Oct 30 2018" "Version 1.95" "IsoSpec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsoSpec::PrecalculatedMarginal \- Precalculated \fBMarginal\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <marginalTrek++\&.h>\fP
.PP
Inherits \fBIsoSpec::Marginal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPrecalculatedMarginal\fP (\fBMarginal\fP &&m, double lCutOff, bool sort=true, int tabSize=1000, int hashSize=1000)"
.br
.RI "The move constructor (disowns the \fBMarginal\fP)\&. "
.ti -1c
.RI "virtual \fB~PrecalculatedMarginal\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "bool \fBinRange\fP (unsigned int idx) const"
.br
.RI "Is there a subisotopologue with a given number? "
.ti -1c
.RI "const double & \fBget_lProb\fP (int idx) const"
.br
.RI "Get the log-probability of the idx-th subisotopologue\&. "
.ti -1c
.RI "const double & \fBget_eProb\fP (int idx) const"
.br
.RI "Get the probability of the idx-th subisotopologue\&. "
.ti -1c
.RI "const double & \fBget_mass\fP (int idx) const"
.br
.RI "Get the mass of the idx-th subisotopologue\&. "
.ti -1c
.RI "const double * \fBget_lProbs_ptr\fP () const"
.br
.RI "Get the table of the log-probabilities of subisotopologues\&. "
.ti -1c
.RI "const double * \fBget_masses_ptr\fP () const"
.br
.RI "Get the table of the masses of subisotopologues\&. "
.ti -1c
.RI "const Conf & \fBget_conf\fP (int idx) const"
.br
.RI "Get the counts of isotopes that define the subisotopologue\&. "
.ti -1c
.RI "unsigned int \fBget_no_confs\fP () const"
.br
.RI "Get the number of precomputed subisotopologues\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< Conf > \fBconfigurations\fP"
.br
.ti -1c
.RI "Conf * \fBconfs\fP"
.br
.ti -1c
.RI "unsigned int \fBno_confs\fP"
.br
.ti -1c
.RI "double * \fBmasses\fP"
.br
.ti -1c
.RI "double * \fBlProbs\fP"
.br
.ti -1c
.RI "double * \fBeProbs\fP"
.br
.ti -1c
.RI "\fBAllocator\fP< int > \fBallocator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Precalculated \fBMarginal\fP class\&. 

This class serves to calculate a set of isotopologues that is defined by the minimal probability threshold\&.
.PP
This works faster than if you did not know the threshold\&. If you have no idea about the threshold, you would need to call us, to change encode the layered version of the marginal\&. 
.PP
Definition at line 213 of file marginalTrek++\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IsoSpec::PrecalculatedMarginal::PrecalculatedMarginal (\fBMarginal\fP && m, double lCutOff, bool sort = \fCtrue\fP, int tabSize = \fC1000\fP, int hashSize = \fC1000\fP)"

.PP
The move constructor (disowns the \fBMarginal\fP)\&. This constructor memoizes all subisotopologues with log-probability above the provided threshold lCutOff 
.PP
\fBParameters:\fP
.RS 4
\fI\fBMarginal\fP\fP An instance of the \fBMarginal\fP class this class is about to disown\&. 
.br
\fIlCutOff\fP The lower limit on the log-probability of the precomputed subisotopologues\&. 
.br
\fIsort\fP Should the subisotopologues be stored with descending probability ? 
.RE
.PP
\fBReturns:\fP
.RS 4
An instance of the \fBPrecalculatedMarginal\fP class\&. 
.RE
.PP

.PP
Definition at line 362 of file marginalTrek++\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "const Conf& IsoSpec::PrecalculatedMarginal::get_conf (int idx) const\fC [inline]\fP"

.PP
Get the counts of isotopes that define the subisotopologue\&. 
.PP
\fBParameters:\fP
.RS 4
\fIidx\fP The number of the considered subisotopologue\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The counts of isotopes that define the subisotopologue\&. 
.RE
.PP

.PP
Definition at line 288 of file marginalTrek++\&.h\&.
.SS "const double& IsoSpec::PrecalculatedMarginal::get_eProb (int idx) const\fC [inline]\fP"

.PP
Get the probability of the idx-th subisotopologue\&. 
.PP
\fBParameters:\fP
.RS 4
\fIidx\fP The number of the considered subisotopologue\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The probability of the idx-th subisotopologue\&. 
.RE
.PP

.PP
Definition at line 261 of file marginalTrek++\&.h\&.
.SS "const double& IsoSpec::PrecalculatedMarginal::get_lProb (int idx) const\fC [inline]\fP"

.PP
Get the log-probability of the idx-th subisotopologue\&. 
.PP
\fBParameters:\fP
.RS 4
\fIidx\fP The number of the considered subisotopologue\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The log-probability of the idx-th subisotopologue\&. 
.RE
.PP

.PP
Definition at line 254 of file marginalTrek++\&.h\&.
.SS "const double* IsoSpec::PrecalculatedMarginal::get_lProbs_ptr () const\fC [inline]\fP"

.PP
Get the table of the log-probabilities of subisotopologues\&. 
.PP
\fBReturns:\fP
.RS 4
Pointer to the first element in the table storing log-probabilities of subisotopologues\&. 
.RE
.PP

.PP
Definition at line 274 of file marginalTrek++\&.h\&.
.SS "const double& IsoSpec::PrecalculatedMarginal::get_mass (int idx) const\fC [inline]\fP"

.PP
Get the mass of the idx-th subisotopologue\&. 
.PP
\fBParameters:\fP
.RS 4
\fIidx\fP The number of the considered subisotopologue\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The mass of the idx-th subisotopologue\&. 
.RE
.PP

.PP
Definition at line 268 of file marginalTrek++\&.h\&.
.SS "const double* IsoSpec::PrecalculatedMarginal::get_masses_ptr () const\fC [inline]\fP"

.PP
Get the table of the masses of subisotopologues\&. 
.PP
\fBReturns:\fP
.RS 4
Pointer to the first element in the table storing masses of subisotopologues\&. 
.RE
.PP

.PP
Definition at line 280 of file marginalTrek++\&.h\&.
.SS "unsigned int IsoSpec::PrecalculatedMarginal::get_no_confs () const\fC [inline]\fP"

.PP
Get the number of precomputed subisotopologues\&. 
.PP
\fBReturns:\fP
.RS 4
The number of precomputed subisotopologues\&. 
.RE
.PP

.PP
Definition at line 294 of file marginalTrek++\&.h\&.
.SS "bool IsoSpec::PrecalculatedMarginal::inRange (unsigned int idx) const\fC [inline]\fP"

.PP
Is there a subisotopologue with a given number? 
.PP
\fBReturns:\fP
.RS 4
Returns true if idx does not exceed the number of pre-computed configurations\&. 
.RE
.PP

.PP
Definition at line 247 of file marginalTrek++\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IsoSpec from the source code\&.
