.TH "IsoSpec::IsoSpec::ConfOrderMarginalDescending" 3 "Thu Oct 11 2018" "Version 1.95" "IsoSpec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsoSpec::IsoSpec::ConfOrderMarginalDescending \- The class used for comparing the position of subisotopologues in the order of descending probabilities\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfOrderMarginalDescending\fP (const double *logProbs, int dim)"
.br
.RI "Contstructor\&. "
.ti -1c
.RI "bool \fBoperator()\fP (const Conf conf1, const Conf conf2)"
.br
.RI "Constructor\&. "
.in -1c
.SH "Detailed Description"
.PP 
The class used for comparing the position of subisotopologues in the order of descending probabilities\&. 

Needed for the priority queue\&. 
.PP
Definition at line 141 of file operators\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IsoSpec::ConfOrderMarginalDescending::ConfOrderMarginalDescending (const double * logProbs, int dim)"

.PP
Contstructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlogProbs\fP 
.br
\fIdim\fP The number of isotopes\&. 
.RE
.PP

.PP
Definition at line 34 of file operators\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool IsoSpec::IsoSpec::ConfOrderMarginalDescending::operator() (const Conf conf1, const Conf conf2)\fC [inline]\fP"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIconf1\fP An array of integer counts\&. 
.br
\fIconf2\fP An array of integer counts\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
True if conf1 is more probable than conf2\&. 
.RE
.PP

.PP
Definition at line 160 of file operators\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IsoSpec from the source code\&.
