.TH "IsoSpec::SSummator" 3 "Tue Oct 30 2018" "Version 1.95" "IsoSpec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsoSpec::SSummator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSSummator\fP (\fBSSummator\fP &other)"
.br
.ti -1c
.RI "void \fBadd\fP (double x)"
.br
.ti -1c
.RI "double \fBget\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file summator\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IsoSpec from the source code\&.
