.TH "IsoSpec::IsoSpec::ReverseOrder< T >" 3 "Thu Oct 11 2018" "Version 1.95" "IsoSpec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsoSpec::IsoSpec::ReverseOrder< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const T a, const T b) const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class IsoSpec::IsoSpec::ReverseOrder< T >"

.PP
Definition at line 167 of file operators\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IsoSpec from the source code\&.
