.TH "IsoSpec::IsoSpec::ConfOrder" 3 "Thu Oct 11 2018" "Version 1.95" "IsoSpec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsoSpec::IsoSpec::ConfOrder \- The class used for comparing the position of configurations in the order of descending probabilities\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (void *conf1, void *conf2) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
The class used for comparing the position of configurations in the order of descending probabilities\&. 

Needed for the priority queue\&. 
.PP
Definition at line 98 of file operators\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IsoSpec from the source code\&.
