.TH "IsoSpec::ThreadSummator" 3 "Thu Oct 11 2018" "Version 1.95" "IsoSpec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsoSpec::ThreadSummator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThreadSummator\fP ()"
.br
.RI "Constructor (sum defaults to zero)\&. "
.ti -1c
.RI "void \fBadd\fP (double what)"
.br
.RI "Add a number to the existing sum\&. "
.ti -1c
.RI "double \fBget\fP ()"
.br
.RI "Get the current value of the sum of the added floating point numbers\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 139 of file summator\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void IsoSpec::ThreadSummator::add (double what)\fC [inline]\fP"

.PP
Add a number to the existing sum\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP A double floating point number to add\&. 
.RE
.PP

.PP
Definition at line 151 of file summator\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IsoSpec from the source code\&.
