.TH "IsoSpec::Marginal" 3 "Tue Oct 30 2018" "Version 1.95" "IsoSpec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsoSpec::Marginal \- The marginal distribution class (a subisotopologue)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <marginalTrek++\&.h>\fP
.PP
Inherited by \fBIsoSpec::MarginalTrek\fP, and \fBIsoSpec::PrecalculatedMarginal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMarginal\fP (const double *_masses, const double *_probs, int _isotopeNo, int _atomCnt)"
.br
.RI "Class constructor\&. "
.ti -1c
.RI "\fBMarginal\fP (\fBMarginal\fP &other)=delete"
.br
.ti -1c
.RI "\fBMarginal\fP & \fBoperator=\fP (const \fBMarginal\fP &other)=delete"
.br
.ti -1c
.RI "\fBMarginal\fP (\fBMarginal\fP &&other)"
.br
.RI "Move constructor\&. "
.ti -1c
.RI "virtual \fB~Marginal\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "int \fBget_isotopeNo\fP () const"
.br
.RI "Get the number of isotopes of the investigated element\&. "
.ti -1c
.RI "double \fBgetLightestConfMass\fP () const"
.br
.RI "Get the mass of the lightest subisotopologue\&. "
.ti -1c
.RI "double \fBgetHeaviestConfMass\fP () const"
.br
.RI "Get the mass of the heaviest subisotopologue\&. "
.ti -1c
.RI "double \fBgetModeLProb\fP () const"
.br
.RI "Get the log-probability of the mode subisotopologue\&. "
.ti -1c
.RI "double \fBgetModeMass\fP () const"
.br
.RI "The the mass of the mode subisotopologue\&. "
.ti -1c
.RI "double \fBgetModeProb\fP () const"
.br
.RI "The the probability of the mode subisotopologue\&. "
.ti -1c
.RI "double \fBgetSmallestLProb\fP () const"
.br
.RI "The the log-probability of the lightest subisotopologue\&. "
.ti -1c
.RI "double \fBlogProb\fP (Conf conf) const"
.br
.RI "Calculate the log-probability of a given subisotopologue\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const unsigned int \fBisotopeNo\fP"
.br
.ti -1c
.RI "const unsigned int \fBatomCnt\fP"
.br
.ti -1c
.RI "const double *const \fBatom_masses\fP"
.br
.ti -1c
.RI "const double *const \fBatom_lProbs\fP"
.br
.ti -1c
.RI "const double \fBloggamma_nominator\fP"
.br
.ti -1c
.RI "const Conf \fBmode_conf\fP"
.br
.ti -1c
.RI "const double \fBmode_lprob\fP"
.br
.ti -1c
.RI "const double \fBmode_mass\fP"
.br
.ti -1c
.RI "const double \fBmode_prob\fP"
.br
.ti -1c
.RI "const double \fBsmallest_lprob\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The marginal distribution class (a subisotopologue)\&. 

This class mostly provides some basic common API for subclasses, but itself is not abstract\&. This class represents the probability distribution generated by one element only -- a subisotopologue\&. For instance, it might be the distribution of C200, that might be part of, say, C200H402\&. It corresponds to the multinomial distribution, where each configuration can also be attributed a precise mass\&. The constructor method perform initial hill-climbing to find the most probable sub-isotopologue (the mode)\&. 
.PP
Definition at line 45 of file marginalTrek++\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IsoSpec::Marginal::Marginal (const double * _masses, const double * _probs, int _isotopeNo, int _atomCnt)"

.PP
Class constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fI_masses\fP A table of masses of the stable isotopes of the investigated element, e\&.g\&. for C10 it is 2: C12 and C13\&. 
.br
\fI_probs\fP A table of natural frequencies of the stable isotopes of the investigated element, see IUPAC at https://iupac.org/isotopesmatter/ 
.br
\fI_isotopeNo\fP Number of isotopes of a given element\&. 
.br
\fI_atomCnt\fP The number of atoms of the given element, e\&.g\&. 10 for C10\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
An instance of the \fBMarginal\fP class\&. 
.RE
.PP

.PP
Definition at line 187 of file marginalTrek++\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int IsoSpec::Marginal::get_isotopeNo () const\fC [inline]\fP"

.PP
Get the number of isotopes of the investigated element\&. 
.PP
\fBReturns:\fP
.RS 4
The integer number of isotopes of the investigated element\&. 
.RE
.PP

.PP
Definition at line 92 of file marginalTrek++\&.h\&.
.SS "double IsoSpec::Marginal::getHeaviestConfMass () const"

.PP
Get the mass of the heaviest subisotopologue\&. This is trivially obtained by considering all atomNo atoms to be the heaviest isotope possible\&. 
.PP
\fBReturns:\fP
.RS 4
The mass of the heaviest subisotopologue\&. 
.RE
.PP

.PP
Definition at line 246 of file marginalTrek++\&.cpp\&.
.SS "double IsoSpec::Marginal::getLightestConfMass () const"

.PP
Get the mass of the lightest subisotopologue\&. This is trivially obtained by considering all atomNo atoms to be the lightest isotope possible\&. 
.PP
\fBReturns:\fP
.RS 4
The mass of the lightiest subisotopologue\&. 
.RE
.PP

.PP
Definition at line 237 of file marginalTrek++\&.cpp\&.
.SS "double IsoSpec::Marginal::getModeLProb () const\fC [inline]\fP"

.PP
Get the log-probability of the mode subisotopologue\&. 
.PP
\fBReturns:\fP
.RS 4
The log-probability of a/the most probable subisotopologue\&. 
.RE
.PP

.PP
Definition at line 110 of file marginalTrek++\&.h\&.
.SS "double IsoSpec::Marginal::getModeMass () const\fC [inline]\fP"

.PP
The the mass of the mode subisotopologue\&. 
.PP
\fBReturns:\fP
.RS 4
The mass of one of the most probable subisotopologues\&. 
.RE
.PP

.PP
Definition at line 116 of file marginalTrek++\&.h\&.
.SS "double IsoSpec::Marginal::getModeProb () const\fC [inline]\fP"

.PP
The the probability of the mode subisotopologue\&. 
.PP
\fBReturns:\fP
.RS 4
The probability of a/the most probable subisotopologue\&. 
.RE
.PP

.PP
Definition at line 122 of file marginalTrek++\&.h\&.
.SS "double IsoSpec::Marginal::getSmallestLProb () const\fC [inline]\fP"

.PP
The the log-probability of the lightest subisotopologue\&. 
.PP
\fBReturns:\fP
.RS 4
The logarithm of the smallest non-zero probability of a subisotopologue\&. 
.RE
.PP

.PP
Definition at line 129 of file marginalTrek++\&.h\&.
.SS "double IsoSpec::Marginal::logProb (Conf conf) const\fC [inline]\fP"

.PP
Calculate the log-probability of a given subisotopologue\&. 
.PP
\fBParameters:\fP
.RS 4
\fIconf\fP A subisotopologue (a table of integers describing subsequent isotope-counts)\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The log-probability of the input subisotopologue\&. 
.RE
.PP

.PP
Definition at line 136 of file marginalTrek++\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "const double* const IsoSpec::Marginal::atom_lProbs\fC [protected]\fP"
Table of log-probabilities of all the isotopeNo isotopes\&. 
.PP
Definition at line 53 of file marginalTrek++\&.h\&.
.SS "const double* const IsoSpec::Marginal::atom_masses\fC [protected]\fP"
Table of atomic masses of all the isotopeNo isotopes\&. 
.PP
Definition at line 52 of file marginalTrek++\&.h\&.
.SS "const unsigned int IsoSpec::Marginal::atomCnt\fC [protected]\fP"
The number of atoms of the given element\&. 
.PP
Definition at line 51 of file marginalTrek++\&.h\&.
.SS "const unsigned int IsoSpec::Marginal::isotopeNo\fC [protected]\fP"
The number of isotopes of the given element\&. 
.PP
Definition at line 50 of file marginalTrek++\&.h\&.
.SS "const double IsoSpec::Marginal::loggamma_nominator\fC [protected]\fP"
The constant nominator that appears in the expressions for the multinomial probabilities\&. 
.PP
Definition at line 54 of file marginalTrek++\&.h\&.
.SS "const Conf IsoSpec::Marginal::mode_conf\fC [protected]\fP"
A subisotopologue with most probability\&. If not unique, one of the representatives of that class of subisotopologues\&. 
.PP
Definition at line 55 of file marginalTrek++\&.h\&.
.SS "const double IsoSpec::Marginal::mode_lprob\fC [protected]\fP"
The log-probability of the mode subisotopologue\&. 
.PP
Definition at line 56 of file marginalTrek++\&.h\&.
.SS "const double IsoSpec::Marginal::mode_mass\fC [protected]\fP"
The mass of the mode subisotopologue\&. 
.PP
Definition at line 57 of file marginalTrek++\&.h\&.
.SS "const double IsoSpec::Marginal::mode_prob\fC [protected]\fP"
The probability of the mode subisotopologue\&. 
.PP
Definition at line 58 of file marginalTrek++\&.h\&.
.SS "const double IsoSpec::Marginal::smallest_lprob\fC [protected]\fP"
The smallest-achievable log-probability in the distribution of subisotopologues\&. 
.PP
Definition at line 59 of file marginalTrek++\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IsoSpec from the source code\&.
