.TH "IsoSpec::KeyHasher" 3 "Tue Oct 30 2018" "Version 1.95" "IsoSpec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsoSpec::KeyHasher
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyHasher\fP (int dim)"
.br
.ti -1c
.RI "std::size_t \fBoperator()\fP (const int *conf) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file operators\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for IsoSpec from the source code\&.
